//  const languageToDefaultVoice: IStringDictionary<string>  = {
//             ["af-ZA"]: "af-ZA-AdriNeural",
//             ["am-ET"]: "am-ET-AmehaNeural",
//             ["ar-AE"]: "ar-AE-FatimaNeural",
//             ["ar-BH"]: "ar-BH-AliNeural",
//             ["ar-DZ"]: "ar-DZ-AminaNeural",
//             ["ar-EG"]: "ar-EG-SalmaNeural",
//             ["ar-IQ"]: "ar-IQ-BasselNeural",
//             ["ar-JO"]: "ar-JO-SanaNeural",
//             ["ar-KW"]: "ar-KW-FahedNeural",
//             ["ar-LY"]: "ar-LY-ImanNeural",
//             ["ar-MA"]: "ar-MA-JamalNeural",
//             ["ar-QA"]: "ar-QA-AmalNeural",
//             ["ar-SA"]: "ar-SA-HamedNeural",
//             ["ar-SY"]: "ar-SY-AmanyNeural",
//             ["ar-TN"]: "ar-TN-HediNeural",
//             ["ar-YE"]: "ar-YE-MaryamNeural",
//             ["bg-BG"]: "bg-BG-BorislavNeural",
//             ["bn-BD"]: "bn-BD-NabanitaNeural",
//             ["bn-IN"]: "bn-IN-BashkarNeural",
//             ["ca-ES"]: "ca-ES-JoanaNeural",
//             ["cs-CZ"]: "cs-CZ-AntoninNeural",
//             ["cy-GB"]: "cy-GB-AledNeural",
//             ["da-DK"]: "da-DK-ChristelNeural",
//             ["de-AT"]: "de-AT-IngridNeural",
//             ["de-CH"]: "de-CH-JanNeural",
//             ["de-DE"]: "de-DE-KatjaNeural",
//             ["el-GR"]: "el-GR-AthinaNeural",
//             ["en-AU"]: "en-AU-NatashaNeural",
//             ["en-CA"]: "en-CA-ClaraNeural",
//             ["en-GB"]: "en-GB-LibbyNeural",
//             ["en-HK"]: "en-HK-SamNeural",
//             ["en-IE"]: "en-IE-ConnorNeural",
//             ["en-IN"]: "en-IN-NeerjaNeural",
//             ["en-KE"]: "en-KE-AsiliaNeural",
//             ["en-NG"]: "en-NG-AbeoNeural",
//             ["en-NZ"]: "en-NZ-MitchellNeural",
//             ["en-PH"]: "en-PH-JamesNeural",
//             ["en-SG"]: "en-SG-LunaNeural",
//             ["en-TZ"]: "en-TZ-ElimuNeural",
//             ["en-US"]: "en-US-JennyNeural",
//             ["en-ZA"]: "en-ZA-LeahNeural",
//             ["es-AR"]: "es-AR-ElenaNeural",
//             ["es-BO"]: "es-BO-MarceloNeural",
//             ["es-CL"]: "es-CL-CatalinaNeural",
//             ["es-CO"]: "es-CO-GonzaloNeural",
//             ["es-CR"]: "es-CR-JuanNeural",
//             ["es-CU"]: "es-CU-BelkysNeural",
//             ["es-DO"]: "es-DO-EmilioNeural",
//             ["es-EC"]: "es-EC-AndreaNeural",
//             ["es-ES"]: "es-ES-AlvaroNeural",
//             ["es-GQ"]: "es-GQ-JavierNeural",
//             ["es-GT"]: "es-GT-AndresNeural",
//             ["es-HN"]: "es-HN-CarlosNeural",
//             ["es-MX"]: "es-MX-DaliaNeural",
//             ["es-NI"]: "es-NI-FedericoNeural",
//             ["es-PA"]: "es-PA-MargaritaNeural",
//             ["es-PE"]: "es-PE-AlexNeural",
//             ["es-PR"]: "es-PR-KarinaNeural",
//             ["es-PY"]: "es-PY-MarioNeural",
//             ["es-SV"]: "es-SV-LorenaNeural",
//             ["es-US"]: "es-US-AlonsoNeural",
//             ["es-UY"]: "es-UY-MateoNeural",
//             ["es-VE"]: "es-VE-PaolaNeural",
//             ["et-EE"]: "et-EE-AnuNeural",
//             ["fa-IR"]: "fa-IR-DilaraNeural",
//             ["fi-FI"]: "fi-FI-SelmaNeural",
//             ["fil-PH"]: "fil-PH-AngeloNeural",
//             ["fr-BE"]: "fr-BE-CharlineNeural",
//             ["fr-CA"]: "fr-CA-SylvieNeural",
//             ["fr-CH"]: "fr-CH-ArianeNeural",
//             ["fr-FR"]: "fr-FR-DeniseNeural",
//             ["ga-IE"]: "ga-IE-ColmNeural",
//             ["gl-ES"]: "gl-ES-RoiNeural",
//             ["gu-IN"]: "gu-IN-DhwaniNeural",
//             ["he-IL"]: "he-IL-AvriNeural",
//             ["hi-IN"]: "hi-IN-MadhurNeural",
//             ["hr-HR"]: "hr-HR-GabrijelaNeural",
//             ["hu-HU"]: "hu-HU-NoemiNeural",
//             ["id-ID"]: "id-ID-ArdiNeural",
//             ["is-IS"]: "is-IS-GudrunNeural",
//             ["it-IT"]: "it-IT-IsabellaNeural",
//             ["ja-JP"]: "ja-JP-NanamiNeural",
//             ["jv-ID"]: "jv-ID-DimasNeural",
//             ["kk-KZ"]: "kk-KZ-AigulNeural",
//             ["km-KH"]: "km-KH-PisethNeural",
//             ["kn-IN"]: "kn-IN-GaganNeural",
//             ["ko-KR"]: "ko-KR-SunHiNeural",
//             ["lo-LA"]: "lo-LA-ChanthavongNeural",
//             ["lt-LT"]: "lt-LT-LeonasNeural",
//             ["lv-LV"]: "lv-LV-EveritaNeural",
//             ["mk-MK"]: "mk-MK-AleksandarNeural",
//             ["ml-IN"]: "ml-IN-MidhunNeural",
//             ["mr-IN"]: "mr-IN-AarohiNeural",
//             ["ms-MY"]: "ms-MY-OsmanNeural",
//             ["mt-MT"]: "mt-MT-GraceNeural",
//             ["my-MM"]: "my-MM-NilarNeural",
//             ["nb-NO"]: "nb-NO-PernilleNeural",
//             ["nl-BE"]: "nl-BE-ArnaudNeural",
//             ["nl-NL"]: "nl-NL-ColetteNeural",
//             ["pl-PL"]: "pl-PL-AgnieszkaNeural",
//             ["ps-AF"]: "ps-AF-GulNawazNeural",
//             ["pt-BR"]: "pt-BR-FranciscaNeural",
//             ["pt-PT"]: "pt-PT-DuarteNeural",
//             ["ro-RO"]: "ro-RO-AlinaNeural",
//             ["ru-RU"]: "ru-RU-SvetlanaNeural",
//             ["si-LK"]: "si-LK-SameeraNeural",
//             ["sk-SK"]: "sk-SK-LukasNeural",
//             ["sl-SI"]: "sl-SI-PetraNeural",
//             ["so-SO"]: "so-SO-MuuseNeural",
//             ["sr-RS"]: "sr-RS-NicholasNeural",
//             ["su-ID"]: "su-ID-JajangNeural",
//             ["sv-SE"]: "sv-SE-SofieNeural",
//             ["sw-KE"]: "sw-KE-RafikiNeural",
//             ["sw-TZ"]: "sw-TZ-DaudiNeural",
//             ["ta-IN"]: "ta-IN-PallaviNeural",
//             ["ta-LK"]: "ta-LK-KumarNeural",
//             ["ta-SG"]: "ta-SG-AnbuNeural",
//             ["te-IN"]: "te-IN-MohanNeural",
//             ["th-TH"]: "th-TH-PremwadeeNeural",
//             ["tr-TR"]: "tr-TR-AhmetNeural",
//             ["uk-UA"]: "uk-UA-OstapNeural",
//             ["ur-IN"]: "ur-IN-GulNeural",
//             ["ur-PK"]: "ur-PK-AsadNeural",
//             ["uz-UZ"]: "uz-UZ-MadinaNeural",
//             ["vi-VN"]: "vi-VN-HoaiMyNeural",
//             ["zh-CN"]: "zh-CN-XiaoxiaoNeural",
//             ["zh-HK"]: "zh-HK-HiuMaanNeural",
//             ["zh-TW"]: "zh-TW-HsiaoChenNeural",
//             ["zu-ZA"]: "zu-ZA-ThandoNeural",
//         };  

use crate::synthesizer::ssml::Language;

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum Voice {
    AfZaAdriNeural,
    AmEtAmehaNeural,
    ArAeFatimaNeural,
    ArBhAliNeural,
    ArDzAminaNeural,
    ArEgSalmaNeural,
    ArIqBasselNeural,
    ArJoSanaNeural,
    ArKwFahedNeural,
    ArLyImanNeural,
    ArMaJamalNeural,
    ArQaAmalNeural,
    ArSaHamedNeural,
    ArSyAmanyNeural,
    ArTnHediNeural,
    ArYeMaryamNeural,
    BgBgBorislavNeural,
    BnBdNabanitaNeural,
    BnInBashkarNeural,
    CaEsJoanaNeural,
    CsCzAntoninNeural,
    CyGbAledNeural,
    DaDkChristelNeural,
    DeAtIngridNeural,
    DeChJanNeural,
    DeDeKatjaNeural,
    ElGrAthinaNeural,
    EnAuNatashaNeural,
    EnCaClaraNeural,
    #[default]
    EnGbLibbyNeural,
    EnHkSamNeural,
    EnIeConnorNeural,
    EnInNeerjaNeural,
    EnKeAsiliaNeural,
    EnNgAbeoNeural,
    EnNzMitchellNeural,
    EnPhJamesNeural,
    EnSgLunaNeural,
    EnTzElimuNeural,
    EnUsJennyNeural,
    EnZaLeahNeural,
    EsArElenaNeural,
    EsBoMarceloNeural,
    EsClCatalinaNeural,
    EsCoGonzaloNeural,
    EsCrJuanNeural,
    EsCuBelkysNeural,
    EsDoEmilioNeural,
    EsEcAndreaNeural,
    EsEsAlvaroNeural,
    EsGqJavierNeural,
    EsGtAndresNeural,
    EsHnCarlosNeural,
    EsMxDaliaNeural,
    EsNiFedericoNeural,
    EsPaMargaritaNeural,
    EsPeAlexNeural,
    EsPrKarinaNeural,
    EsPyMarioNeural,
    EsSvLorenaNeural,
    EsUsAlonsoNeural,
    EsUyMateoNeural,
    EsVePaolaNeural,
    EtEeAnuNeural,
    FaIrDilaraNeural,
    FiFiSelmaNeural,
    FilPhAngeloNeural,
    FrBeCharlineNeural,
    FrCaSylvieNeural,
    FrChArianeNeural,
    FrFrDeniseNeural,
    GaIeColmNeural,
    GlEsRoiNeural,
    GuInDhwaniNeural,
    HeIlAvriNeural,
    HiInMadhurNeural,
    HrHrGabrijelaNeural,
    HuHuNoemiNeural,
    IdIdArdiNeural,
    IsIsGudrunNeural,
    ItItIsabellaNeural,
    JaJpNanamiNeural,
    JvIdDimasNeural,
    KkKzAigulNeural,
    KmKhPisethNeural,
    KnInGaganNeural,
    KoKrSunHiNeural,
    LoLaChanthavongNeural,
    LtLtLeonasNeural,
    LvLvEveritaNeural,
    MkMkAleksandarNeural,
    MlInMidhunNeural,
    MrInAarohiNeural,
    MsMyOsmanNeural,
    MtMtGraceNeural,
    MyMmNilarNeural,
    NbNoPernilleNeural,
    NlBeArnaudNeural,
    NlNlColetteNeural,
    PlPlAgnieszkaNeural,
    PsAfGulNawazNeural,
    PtBrFranciscaNeural,
    PtPtDuarteNeural,
    RoRoAlinaNeural,
    RuRuSvetlanaNeural,
    SiLkSameeraNeural,
    SkSkLukasNeural,
    SlSiPetraNeural,
    SoSoMuuseNeural,
    SrRsNicholasNeural,
    SuIdJajangNeural,
    SvSeSofieNeural,
    SwKeRafikiNeural,
    SwTzDaudiNeural,
    TaInPallaviNeural,
    TaLkKumarNeural,
    TaSgAnbuNeural,
    TeInMohanNeural,
    ThThPremwadeeNeural,
    TrTrAhmetNeural,
    UkUaOstapNeural,
    UrInGulNeural,
    UrPkAsadNeural,
    UzUzMadinaNeural,
    ViVnHoaiMyNeural,
    ZhCnXiaoxiaoNeural,
    ZhHkHiuMaanNeural,
    ZhTwHsiaoChenNeural,
    ZuZaThandoNeural,
    Specific(&'static str),
}

impl Voice {
    pub fn as_str(&self) -> &'static str {
        match *self {
            Voice::AfZaAdriNeural => "af-ZA-AdriNeural",
            Voice::AmEtAmehaNeural => "am-ET-AmehaNeural",
            Voice::ArAeFatimaNeural => "ar-AE-FatimaNeural",
            Voice::ArBhAliNeural => "ar-BH-AliNeural",
            Voice::ArDzAminaNeural => "ar-DZ-AminaNeural",
            Voice::ArEgSalmaNeural => "ar-EG-SalmaNeural",
            Voice::ArIqBasselNeural => "ar-IQ-BasselNeural",
            Voice::ArJoSanaNeural => "ar-JO-SanaNeural",
            Voice::ArKwFahedNeural => "ar-KW-FahedNeural",
            Voice::ArLyImanNeural => "ar-LY-ImanNeural",
            Voice::ArMaJamalNeural => "ar-MA-JamalNeural",
            Voice::ArQaAmalNeural => "ar-QA-AmalNeural",
            Voice::ArSaHamedNeural => "ar-SA-HamedNeural",
            Voice::ArSyAmanyNeural => "ar-SY-AmanyNeural",
            Voice::ArTnHediNeural => "ar-TN-HediNeural",
            Voice::ArYeMaryamNeural => "ar-YE-MaryamNeural",
            Voice::BgBgBorislavNeural => "bg-BG-BorislavNeural",
            Voice::BnBdNabanitaNeural => "bn-BD-NabanitaNeural",
            Voice::BnInBashkarNeural => "bn-IN-BashkarNeural",
            Voice::CaEsJoanaNeural => "ca-ES-JoanaNeural",
            Voice::CsCzAntoninNeural => "cs-CZ-AntoninNeural",
            Voice::CyGbAledNeural => "cy-GB-AledNeural",
            Voice::DaDkChristelNeural => "da-DK-ChristelNeural",
            Voice::DeAtIngridNeural => "de-AT-IngridNeural",
            Voice::DeChJanNeural => "de-CH-JanNeural",
            Voice::DeDeKatjaNeural => "de-DE-KatjaNeural",
            Voice::ElGrAthinaNeural => "el-GR-AthinaNeural",
            Voice::EnAuNatashaNeural => "en-AU-NatashaNeural",
            Voice::EnCaClaraNeural => "en-CA-ClaraNeural",
            Voice::EnGbLibbyNeural => "en-GB-LibbyNeural",
            Voice::EnHkSamNeural => "en-HK-SamNeural",
            Voice::EnIeConnorNeural => "en-IE-ConnorNeural",
            Voice::EnInNeerjaNeural => "en-IN-NeerjaNeural",
            Voice::EnKeAsiliaNeural => "en-KE-AsiliaNeural",
            Voice::EnNgAbeoNeural => "en-NG-AbeoNeural",
            Voice::EnNzMitchellNeural => "en-NZ-MitchellNeural",
            Voice::EnPhJamesNeural => "en-PH-JamesNeural",
            Voice::EnSgLunaNeural => "en-SG-LunaNeural",
            Voice::EnTzElimuNeural => "en-TZ-ElimuNeural",
            Voice::EnUsJennyNeural => "en-US-JennyNeural",
            Voice::EnZaLeahNeural => "en-ZA-LeahNeural",
            Voice::EsArElenaNeural => "es-AR-ElenaNeural",
            Voice::EsBoMarceloNeural => "es-BO-MarceloNeural",
            Voice::EsClCatalinaNeural => "es-CL-CatalinaNeural",
            Voice::EsCoGonzaloNeural => "es-CO-GonzaloNeural",
            Voice::EsCrJuanNeural => "es-CR-JuanNeural",
            Voice::EsCuBelkysNeural => "es-CU-BelkysNeural",
            Voice::EsDoEmilioNeural => "es-DO-EmilioNeural",
            Voice::EsEcAndreaNeural => "es-EC-AndreaNeural",
            Voice::EsEsAlvaroNeural => "es-ES-AlvaroNeural",
            Voice::EsGqJavierNeural => "es-GQ-JavierNeural",
            Voice::EsGtAndresNeural => "es-GT-AndresNeural",
            Voice::EsHnCarlosNeural => "es-HN-CarlosNeural",
            Voice::EsMxDaliaNeural => "es-MX-DaliaNeural",
            Voice::EsNiFedericoNeural => "es-NI-FedericoNeural",
            Voice::EsPaMargaritaNeural => "es-PA-MargaritaNeural",
            Voice::EsPeAlexNeural => "es-PE-AlexNeural",
            Voice::EsPrKarinaNeural => "es-PR-KarinaNeural",
            Voice::EsPyMarioNeural => "es-PY-MarioNeural",
            Voice::EsSvLorenaNeural => "es-SV-LorenaNeural",
            Voice::EsUsAlonsoNeural => "es-US-AlonsoNeural",
            Voice::EsUyMateoNeural => "es-UY-MateoNeural",
            Voice::EsVePaolaNeural => "es-VE-PaolaNeural",
            Voice::EtEeAnuNeural => "et-EE-AnuNeural",
            Voice::FaIrDilaraNeural => "fa-IR-DilaraNeural",
            Voice::FiFiSelmaNeural => "fi-FI-SelmaNeural",
            Voice::FilPhAngeloNeural => "fil-PH-AngeloNeural",
            Voice::FrBeCharlineNeural => "fr-BE-CharlineNeural",
            Voice::FrCaSylvieNeural => "fr-CA-SylvieNeural",
            Voice::FrChArianeNeural => "fr-CH-ArianeNeural",
            Voice::FrFrDeniseNeural => "fr-FR-DeniseNeural",
            Voice::GaIeColmNeural => "ga-IE-ColmNeural",
            Voice::GlEsRoiNeural => "gl-ES-RoiNeural",
            Voice::GuInDhwaniNeural => "gu-IN-DhwaniNeural",
            Voice::HeIlAvriNeural => "he-IL-AvriNeural",
            Voice::HiInMadhurNeural => "hi-IN-MadhurNeural",
            Voice::HrHrGabrijelaNeural => "hr-HR-GabrijelaNeural",
            Voice::HuHuNoemiNeural => "hu-HU-NoemiNeural",
            Voice::IdIdArdiNeural => "id-ID-ArdiNeural",
            Voice::IsIsGudrunNeural => "is-IS-GudrunNeural",
            Voice::ItItIsabellaNeural => "it-IT-IsabellaNeural",
            Voice::JaJpNanamiNeural => "ja-JP-NanamiNeural",
            Voice::JvIdDimasNeural => "jv-ID-DimasNeural",
            Voice::KkKzAigulNeural => "kk-KZ-AigulNeural",
            Voice::KmKhPisethNeural => "km-KH-PisethNeural",
            Voice::KnInGaganNeural => "kn-IN-GaganNeural",
            Voice::KoKrSunHiNeural => "ko-KR-SunHiNeural",
            Voice::LoLaChanthavongNeural => "lo-LA-ChanthavongNeural",
            Voice::LtLtLeonasNeural => "lt-LT-LeonasNeural",
            Voice::LvLvEveritaNeural => "lv-LV-EveritaNeural",
            Voice::MkMkAleksandarNeural => "mk-MK-AleksandarNeural",
            Voice::MlInMidhunNeural => "ml-IN-MidhunNeural",
            Voice::MrInAarohiNeural => "mr-IN-AarohiNeural",
            Voice::MsMyOsmanNeural => "ms-MY-OsmanNeural",
            Voice::MtMtGraceNeural => "mt-MT-GraceNeural",
            Voice::MyMmNilarNeural => "my-MM-NilarNeural",
            Voice::NbNoPernilleNeural => "nb-NO-PernilleNeural",
            Voice::NlBeArnaudNeural => "nl-BE-ArnaudNeural",
            Voice::NlNlColetteNeural => "nl-NL-ColetteNeural",
            Voice::PlPlAgnieszkaNeural => "pl-PL-AgnieszkaNeural",
            Voice::PsAfGulNawazNeural => "ps-AF-GulNawazNeural",
            Voice::PtBrFranciscaNeural => "pt-BR-FranciscaNeural",
            Voice::PtPtDuarteNeural => "pt-PT-DuarteNeural",
            Voice::RoRoAlinaNeural => "ro-RO-AlinaNeural",
            Voice::RuRuSvetlanaNeural => "ru-RU-SvetlanaNeural",
            Voice::SiLkSameeraNeural => "si-LK-SameeraNeural",
            Voice::SkSkLukasNeural => "sk-SK-LukasNeural",
            Voice::SlSiPetraNeural => "sl-SI-PetraNeural",
            Voice::SoSoMuuseNeural => "so-SO-MuuseNeural",
            Voice::SrRsNicholasNeural => "sr-RS-NicholasNeural",
            Voice::SuIdJajangNeural => "su-ID-JajangNeural",
            Voice::SvSeSofieNeural => "sv-SE-SofieNeural",
            Voice::SwKeRafikiNeural => "sw-KE-RafikiNeural",
            Voice::SwTzDaudiNeural => "sw-TZ-DaudiNeural",
            Voice::TaInPallaviNeural => "ta-IN-PallaviNeural",
            Voice::TaLkKumarNeural => "ta-LK-KumarNeural",
            Voice::TaSgAnbuNeural => "ta-SG-AnbuNeural",
            Voice::TeInMohanNeural => "te-IN-MohanNeural",
            Voice::ThThPremwadeeNeural => "th-TH-PremwadeeNeural",
            Voice::TrTrAhmetNeural => "tr-TR-AhmetNeural",
            Voice::UkUaOstapNeural => "uk-UA-OstapNeural",
            Voice::UrInGulNeural => "ur-IN-GulNeural",
            Voice::UrPkAsadNeural => "ur-PK-AsadNeural",
            Voice::UzUzMadinaNeural => "uz-UZ-MadinaNeural",
            Voice::ViVnHoaiMyNeural => "vi-VN-HoaiMyNeural",
            Voice::ZhCnXiaoxiaoNeural => "zh-CN-XiaoxiaoNeural",
            Voice::ZhHkHiuMaanNeural => "zh-HK-HiuMaanNeural",
            Voice::ZhTwHsiaoChenNeural => "zh-TW-HsiaoChenNeural",
            Voice::ZuZaThandoNeural => "zu-ZA-ThandoNeural",
            Voice::Specific(s) => s,
        }
    }

    pub fn default_for_language(language: Language) -> Voice {
        match language {
            Language::AutoDetect => Voice::EnUsJennyNeural,
            Language::AfZa => Voice::AfZaAdriNeural,
            Language::AmEt => Voice::AmEtAmehaNeural,
            Language::ArAe => Voice::ArAeFatimaNeural,
            Language::ArBh => Voice::ArBhAliNeural,
            Language::ArDz => Voice::ArDzAminaNeural,
            Language::ArEg => Voice::ArEgSalmaNeural,
            Language::ArIq => Voice::ArIqBasselNeural,
            Language::ArJo => Voice::ArJoSanaNeural,
            Language::ArKw => Voice::ArKwFahedNeural,
            Language::ArLy => Voice::ArLyImanNeural,
            Language::ArMa => Voice::ArMaJamalNeural,
            Language::ArQa => Voice::ArQaAmalNeural,
            Language::ArSa => Voice::ArSaHamedNeural,
            Language::ArSy => Voice::ArSyAmanyNeural,
            Language::ArTn => Voice::ArTnHediNeural,
            Language::ArYe => Voice::ArYeMaryamNeural,
            Language::BgBg => Voice::BgBgBorislavNeural,
            Language::BnBd => Voice::BnBdNabanitaNeural,
            Language::BnIn => Voice::BnInBashkarNeural,
            Language::CaEs => Voice::CaEsJoanaNeural,
            Language::CsCz => Voice::CsCzAntoninNeural,
            Language::CyGb => Voice::CyGbAledNeural,
            Language::DaDk => Voice::DaDkChristelNeural,
            Language::DeAt => Voice::DeAtIngridNeural,
            Language::DeCh => Voice::DeChJanNeural,
            Language::DeDe => Voice::DeDeKatjaNeural,
            Language::ElGr => Voice::ElGrAthinaNeural,
            Language::EnAu => Voice::EnAuNatashaNeural,
            Language::EnCa => Voice::EnCaClaraNeural,
            Language::EnGb => Voice::EnGbLibbyNeural,
            Language::EnHk => Voice::EnHkSamNeural,
            Language::EnIe => Voice::EnIeConnorNeural,
            Language::EnIn => Voice::EnInNeerjaNeural,
            Language::EnKe => Voice::EnKeAsiliaNeural,
            Language::EnNg => Voice::EnNgAbeoNeural,
            Language::EnNz => Voice::EnNzMitchellNeural,
            Language::EnPh => Voice::EnPhJamesNeural,
            Language::EnSg => Voice::EnSgLunaNeural,
            Language::EnTz => Voice::EnTzElimuNeural,
            Language::EnUs => Voice::EnUsJennyNeural,
            Language::EnZa => Voice::EnZaLeahNeural,
            Language::EsAr => Voice::EsArElenaNeural,
            Language::EsBo => Voice::EsBoMarceloNeural,
            Language::EsCl => Voice::EsClCatalinaNeural,
            Language::EsCo => Voice::EsCoGonzaloNeural,
            Language::EsCr => Voice::EsCrJuanNeural,
            Language::EsCu => Voice::EsCuBelkysNeural,
            Language::EsDo => Voice::EsDoEmilioNeural,
            Language::EsEc => Voice::EsEcAndreaNeural,
            Language::EsEs => Voice::EsEsAlvaroNeural,
            Language::EsGq => Voice::EsGqJavierNeural,
            Language::EsGt => Voice::EsGtAndresNeural,
            Language::EsHn => Voice::EsHnCarlosNeural,
            Language::EsMx => Voice::EsMxDaliaNeural,
            Language::EsNi => Voice::EsNiFedericoNeural,
            Language::EsPa => Voice::EsPaMargaritaNeural,
            Language::EsPe => Voice::EsPeAlexNeural,
            Language::EsPr => Voice::EsPrKarinaNeural,
            Language::EsPy => Voice::EsPyMarioNeural,
            Language::EsSv => Voice::EsSvLorenaNeural,
            Language::EsUs => Voice::EsUsAlonsoNeural,
            Language::EsUy => Voice::EsUyMateoNeural,
            Language::EsVe => Voice::EsVePaolaNeural,
            Language::EtEe => Voice::EtEeAnuNeural,
            Language::FaIr => Voice::FaIrDilaraNeural,
            Language::FiFi => Voice::FiFiSelmaNeural,
            Language::FilPh => Voice::FilPhAngeloNeural,
            Language::FrBe => Voice::FrBeCharlineNeural,
            Language::FrCa => Voice::FrCaSylvieNeural,
            Language::FrCh => Voice::FrChArianeNeural,
            Language::FrFr => Voice::FrFrDeniseNeural,
            Language::GaIe => Voice::GaIeColmNeural,
            Language::GlEs => Voice::GlEsRoiNeural,
            Language::GuIn => Voice::GuInDhwaniNeural,
            Language::HeIl => Voice::HeIlAvriNeural,
            Language::HiIn => Voice::HiInMadhurNeural,
            Language::HrHr => Voice::HrHrGabrijelaNeural,
            Language::HuHu => Voice::HuHuNoemiNeural,
            Language::IdId => Voice::IdIdArdiNeural,
            Language::IsIs => Voice::IsIsGudrunNeural,
            Language::ItIt => Voice::ItItIsabellaNeural,
            Language::JaJp => Voice::JaJpNanamiNeural,
            Language::JvId => Voice::JvIdDimasNeural,
            Language::KkKz => Voice::KkKzAigulNeural,
            Language::KmKh => Voice::KmKhPisethNeural,
            Language::KnIn => Voice::KnInGaganNeural,
            Language::KoKr => Voice::KoKrSunHiNeural,
            Language::LoLa => Voice::LoLaChanthavongNeural,
            Language::LtLt => Voice::LtLtLeonasNeural,
            Language::LvLv => Voice::LvLvEveritaNeural,
            Language::MkMk => Voice::MkMkAleksandarNeural,
            Language::MlIn => Voice::MlInMidhunNeural,
            Language::MrIn => Voice::MrInAarohiNeural,
            Language::MsMy => Voice::MsMyOsmanNeural,
            Language::MtMt => Voice::MtMtGraceNeural,
            Language::MyMm => Voice::MyMmNilarNeural,
            Language::NbNo => Voice::NbNoPernilleNeural,
            Language::NlBe => Voice::NlBeArnaudNeural,
            Language::NlNl => Voice::NlNlColetteNeural,
            Language::PlPl => Voice::PlPlAgnieszkaNeural,
            Language::PsAf => Voice::PsAfGulNawazNeural,
            Language::PtBr => Voice::PtBrFranciscaNeural,
            Language::PtPt => Voice::PtPtDuarteNeural,
            Language::RoRo => Voice::RoRoAlinaNeural,
            Language::RuRu => Voice::RuRuSvetlanaNeural,
            Language::SiLk => Voice::SiLkSameeraNeural,
            Language::SkSk => Voice::SkSkLukasNeural,
            Language::SlSi => Voice::SlSiPetraNeural,
            Language::SoSo => Voice::SoSoMuuseNeural,
            Language::SrRs => Voice::SrRsNicholasNeural,
            Language::SuId => Voice::SuIdJajangNeural,
            Language::SvSe => Voice::SvSeSofieNeural,
            Language::SwKe => Voice::SwKeRafikiNeural,
            Language::SwTz => Voice::SwTzDaudiNeural,
            Language::TaIn => Voice::TaInPallaviNeural,
            Language::TaLk => Voice::TaLkKumarNeural,
            Language::TaSg => Voice::TaSgAnbuNeural,
            Language::TeIn => Voice::TeInMohanNeural,
            Language::ThTh => Voice::ThThPremwadeeNeural,
            Language::TrTr => Voice::TrTrAhmetNeural,
            Language::UkUa => Voice::UkUaOstapNeural,
            Language::UrIn => Voice::UrInGulNeural,
            Language::UrPk => Voice::UrPkAsadNeural,
            Language::UzUz => Voice::UzUzMadinaNeural,
            Language::ViVn => Voice::ViVnHoaiMyNeural,
            Language::ZhCn => Voice::ZhCnXiaoxiaoNeural,
            Language::ZhHk => Voice::ZhHkHiuMaanNeural,
            Language::ZhTw => Voice::ZhTwHsiaoChenNeural,
            Language::ZuZa => Voice::ZuZaThandoNeural,
        }
    }
}
